In [25]:
import pandas as pd
import numpy as np


pd.set_option('display.max_columns', None)
pd.set_option('display.width', None) 
pd.set_option('display.max_colwidth', 10)

1. Carga e inspección

In [26]:
df = pd.read_csv('laptopData.csv')
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Pa...,Intel ...,8GB,128GB SSD,Intel ...,macOS,1.37kg,71378....
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel ...,8GB,128GB ...,Intel ...,macOS,1.34kg,47895....
2,2.0,HP,Notebook,15.6,Full H...,Intel ...,8GB,256GB SSD,Intel ...,No OS,1.86kg,30636....
3,3.0,Apple,Ultrabook,15.4,IPS Pa...,Intel ...,16GB,512GB SSD,AMD Ra...,macOS,1.83kg,135195...
4,4.0,Apple,Ultrabook,13.3,IPS Pa...,Intel ...,8GB,256GB SSD,Intel ...,macOS,1.37kg,96095....

In [46]:
df.shape

(1273, 11)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1273 entries, 0 to 1302
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   compania             1273 non-null   object
 1   tipo_laptop          1273 non-null   object
 2   pulgadas             1272 non-null   float64
 3   resolucion_pantalla  1273 non-null   object
 4   procesador           1273 non-null   object
 5   Ram                  1273 non-null   object
 6   memoria              1273 non-null   object
 7   tarjeta_grafica      1273 non-null   object
 8   sistema_operativo    1273 non-null   object
 9   peso                 1273 non-null   object
 10  precio               1273 non-null   float64
dtypes: float64(2), object(9)
memory usage: 119.3+ KB

In [48]:
print(df.columns)
df.head()

Index(['compania', 'tipo_laptop', 'pulgadas', 'resolucion_pantalla',
       'procesador', 'Ram', 'memoria', 'tarjeta_grafica', 'sistema_operativo',
       'peso', 'precio'],
      dtype='object')

,compania,tipo_laptop,pulgadas,resolucion_pantalla,procesador,Ram,memoria,tarjeta_grafica,sistema_operativo,peso,precio
0,Apple,Ultrabook,13.3,IPS Pa...,Intel ...,8GB,128GB SSD,Intel ...,macOS,1.37kg,71378....
1,Apple,Ultrabook,13.3,1440x900,Intel ...,8GB,128GB ...,Intel ...,macOS,1.34kg,47895....
2,HP,Notebook,15.6,Full H...,Intel ...,8GB,256GB SSD,Intel ...,No OS,1.86kg,30636....
3,Apple,Ultrabook,15.4,IPS Pa...,Intel ...,16GB,512GB SSD,AMD Ra...,macOS,1.83kg,135195...
4,Apple,Ultrabook,13.3,IPS Pa...,Intel ...,8GB,256GB SSD,Intel ...,macOS,1.37kg,96095....

In [49]:
df.rename(columns={'Unnamed: 0': 'id', 'Company': 'compania', 'TypeName': 'tipo_laptop', 'Inches': 'pulgadas', 'ScreenResolution': 'resolucion_pantalla', 'Cpu': 'procesador', 'Gpu': 'tarjeta_grafica', 'OpSys': 'sistema_operativo', 'Weight': 'peso', 'Price': 'precio'}, inplace=True)

In [50]:
df.rename(columns={'Memory': 'memoria'}, inplace=True)

In [51]:
df.head()

,compania,tipo_laptop,pulgadas,resolucion_pantalla,procesador,Ram,memoria,tarjeta_grafica,sistema_operativo,peso,precio
0,Apple,Ultrabook,13.3,IPS Pa...,Intel ...,8GB,128GB SSD,Intel ...,macOS,1.37kg,71378....
1,Apple,Ultrabook,13.3,1440x900,Intel ...,8GB,128GB ...,Intel ...,macOS,1.34kg,47895....
2,HP,Notebook,15.6,Full H...,Intel ...,8GB,256GB SSD,Intel ...,No OS,1.86kg,30636....
3,Apple,Ultrabook,15.4,IPS Pa...,Intel ...,16GB,512GB SSD,AMD Ra...,macOS,1.83kg,135195...
4,Apple,Ultrabook,13.3,IPS Pa...,Intel ...,8GB,256GB SSD,Intel ...,macOS,1.37kg,96095....

In [52]:
df.isna().sum()

compania               0
tipo_laptop            0
pulgadas               1
resolucion_pantalla    0
procesador             0
Ram                    0
memoria                0
tarjeta_grafica        0
sistema_operativo      0
peso                   0
precio                 0
dtype: int64

In [53]:
df['precio'].describe(include='all')

count    1273.0...
mean     59955....
std      37332....
min      9270.7...
25%      31914....
50%      52161....
75%      79333....
max      324954...
Name: precio, dtype: float64

2. Limpieza y transformación basica

In [58]:
df.isna().sum()

compania               0
tipo_laptop            0
pulgadas               0
resolucion_pantalla    0
procesador             0
Ram                    0
memoria                0
tarjeta_grafica        0
sistema_operativo      0
peso                   0
precio                 0
dtype: int64

In [55]:
##Elimino la columna id porque no aporta nada a mi análisis y tiene muchos valores nulos.
df.drop('id', axis=1, inplace=True, errors='ignore')

In [59]:
##Eliminamos todas las filas que contienen valores nulos, ya que no son muchas y no queremos imputar datos.
df.dropna(inplace=True)

In [60]:
pulgadas = df['pulgadas'].unique()
print(pulgadas)

[13.3 15.6 15.4 14.  12.  17.3 13.5 12.5 13.  18.4 13.9 11.6 25.6 35.6
 12.3 27.3 24.  33.5 31.6 17.  15.  14.1 11.3 10.1]

In [61]:
###Convertimos la columna 'pulgadas' a tipo numérico, forzando los errores a NaN para manejar cualquier valor no convertible.
df['pulgadas'] = pd.to_numeric(df['pulgadas'], errors='coerce')

In [62]:
df.head()

,compania,tipo_laptop,pulgadas,resolucion_pantalla,procesador,Ram,memoria,tarjeta_grafica,sistema_operativo,peso,precio
0,Apple,Ultrabook,13.3,IPS Pa...,Intel ...,8GB,128GB SSD,Intel ...,macOS,1.37kg,71378....
1,Apple,Ultrabook,13.3,1440x900,Intel ...,8GB,128GB ...,Intel ...,macOS,1.34kg,47895....
2,HP,Notebook,15.6,Full H...,Intel ...,8GB,256GB SSD,Intel ...,No OS,1.86kg,30636....
3,Apple,Ultrabook,15.4,IPS Pa...,Intel ...,16GB,512GB SSD,AMD Ra...,macOS,1.83kg,135195...
4,Apple,Ultrabook,13.3,IPS Pa...,Intel ...,8GB,256GB SSD,Intel ...,macOS,1.37kg,96095....

In [41]:
###Resultado del codigo anterior antes de reemplazar el valor '?':

###['13.3' '15.6' '15.4' '14' '12' '17.3' '13.5' '12.5' '13' '18.4' '13.9'
###'11.6' '25.6' '35.6' '12.3' '27.3' '24' '33.5' '?' '31.6' '17' '15'
###'14.1' '11.3' '10.1']

In [92]:
df[df['pulgadas'] == '?']

Empty DataFrame
Columns: [compania, tipo_laptop, pulgadas, resolucion_pantalla, procesador, Ram, memoria, tarjeta_grafica, sistema_operativo, peso, precio]
Index: []

In [64]:
df[df['pulgadas'] == '25.6']

Empty DataFrame
Columns: [compania, tipo_laptop, pulgadas, resolucion_pantalla, procesador, Ram, memoria, tarjeta_grafica, sistema_operativo, peso, precio]
Index: []

In [74]:
	###Resultado: 1 fila con valor '?', que corresponde a un Dell Precision 7520 FHD 15.6" Workstation Business PC (Intel Quad Core i7-7700HQ, 16GB Ram, 256GB SSD, Thunderbolt 3) Nvidia Quadro M1200 4GB DDR5. Por lo tanto, reemplazamos el valor '?' por '15.6', que es el tamaño de pantalla de ese modelo.

     ##compania	tipo_laptop	pulgadas	resolucion_pantalla	procesador	Ram	memoria	tarjeta_grafica	sistema_operativo	peso	precio
###476	Dell	Workst...	?	Full H...	Intel ...	8GB	256GB SSD	Nvidia...	Window...	1.78kg	128298.24

In [93]:
###Dell Precision 7520 FHD 15.6" Workstation Business PC (Intel Quad Core i7-7700HQ, 16GB Ram, 256GB SSD, Thunderbolt 3) Nvidia Quadro M1200 4GB DDR5
df['pulgadas'] = df['pulgadas'].str.replace('?', '15.6', regex=False)

AttributeError: Can only use .str accessor with string values!

In [ ]:
###Podria colocar Unknown o Desconocido, pero no lo hago porque las configuraciones de los equipos son diferentees y afectarian el analisis

##df['compania'].fillna('unknown', inplace=True)
##df['tipo_laptop'].fillna('unknown', inplace=True)
##df['pulgadas'].fillna('unknown', inplace=True)
##df['resolucion'].fillna('unknown', inplace=True)
##df['procesador'].fillna('unknown', inplace=True)
##df['tarjeta_grafica'].fillna('unknown', inplace=True)
##df['sistema_operativo'].fillna('unknown', inplace=True)
##df['peso'].fillna('unknown', inplace=True)
## df['precio'].fillna('unknown', inplace=True)

In [90]:
df['tipo_laptop'].value_counts()

tipo_laptop
Notebook              710
Gaming                203
Ultrabook             189
2 in 1 Convertible    112
Workstation            28
Name: count, dtype: int64

In [67]:
##Corregimos el error de tipeo en la columna tipo_laptop, cambiando Netbook por Notebook
df['tipo_laptop'] = df['tipo_laptop'].str.replace('Netbook', 'Notebook', regex=False)

In [68]:
df['compania'].value_counts()

compania
Lenovo       290
Dell         286
HP           266
Asus         156
Acer         103
MSI           53
Toshiba       47
Apple         21
Samsung        9
Mediacom       7
Razer          7
Microsoft      6
Vero           4
Xiaomi         4
Chuwi          3
LG             3
Google         3
Huawei         2
Fujitsu        2
Name: count, dtype: int64

In [ ]:
##Cambiamos la referncia de Vero por Acer, ya que es un error de tipeo y no existe la marca Vero y es una linea de la marca Acer
df['compania'] = df['compania'].str.replace('Vero', 'Acer', regex=False)

In [88]:
##Cambiamos peso a tipo numérico, eliminando la unidad 'kg' y convirtiendo a float
df['peso'] = df['peso'].str.replace('kg', '', regex=False)

##Cambiamos el precio a tipo numérico, eliminando el símbolo de moneda y convirtiendo a float

In [89]:
##Revisamos los valores únicos de la columna peso para verificar que se hayan limpiado correctamente y que no haya quedado ningún valor no numérico.
peso = df['peso'].unique()
print(peso)


 ##'2.54' '3.42' '5.8' '1.28' '2.33' '1.45' '2.79' '8.23' '1.26' '1.84'
 ##'0.0002' '2.6' '2.26' '3.25' '1.59' '1.13' '1.42' '1.78' '1.10' '1.15'
 ##'1.27' '1.43' '2.31' '1.16' '1.64' '2.17' '1.47' '3.78' '1.79' '0.91'

['1.37' '1.34' '1.86' '1.83' '2.1' '2.04' '1.3' '1.6' '2.2' '0.92' '1.22'
 '2.5' '1.62' '1.91' '2.3' '1.35' '1.88' '1.89' '1.65' '2.71' '1.2' '1.44'
 '2.8' '2' '2.65' '2.77' '3.2' '1.49' '2.4' '2.13' '2.43' '1.7' '1.4'
 '1.8' '1.9' '3' '1.252' '2.7' '2.02' '1.63' '1.96' '1.21' '2.45' '1.25'
 '1.5' '2.62' '1.38' '1.58' '1.85' '1.23' '2.16' '2.36' '7.2' '2.05'
 '1.32' '1.75' '0.97' '2.56' '1.48' '1.74' '1.1' '1.56' '2.03' '1.05'
 '5.4' '4.4' '1.90' '1.29' '2.0' '1.95' '2.06' '1.12' '3.49' '3.35' '2.23'
 '?' '2.9' '4.42' '2.69' '2.37' '4.7' '3.6' '2.08' '4.3' '1.68' '1.41'
 '4.14' '2.18' '2.24' '2.67' '4.1' '2.14' '1.36' '2.25' '2.15' '2.19'
 '2.54' '3.42' '5.8' '1.28' '2.33' '1.45' '2.79' '8.23' '1.26' '1.84'
 '2.6' '2.26' '3.25' '1.59' '1.13' '1.42' '1.78' '1.10' '1.15' '1.27'
 '1.43' '2.31' '1.16' '1.64' '2.17' '1.47' '3.78' '1.79' '0.91' '1.99'
 '4.33' '1.93' '1.87' '2.63' '3.4' '3.14' '1.94' '1.24' '4.6' '4.5' '8.4'
 '2.73' '1.39' '2.29' '2.59' '2.94' '11.1' '1.14' '3.8' '6.2' '3.31'
 '1.09' '3.21' '1.19' '1.98' '1.17' '4.36' '1.71' '2.32' '4.2' '1.55'
 '0.81' '1.18' '2.72' '1.31' '0.920' '3.74' '1.76' '1.54' '2.83' '2.07'
 '2.38' '3.58' '1.08' '2.20' '0.98' '2.75' '1.70' '2.99' '1.11' '2.09' '4'
 '3.0' '0.99' '0.69' '3.52' '2.591' '2.21' '3.3' '2.191' '2.34' '4.0']

In [86]:
##Como hay un valor de 0.0002 kg, que es claramente un error de tipeo, lo reemplazamos por 0.2 kg, que es un valor más razonable para el peso de una laptop.
df['peso'] = df['peso'].str.replace('0.0002', '2.0', regex=False)

In [84]:
peso= df['peso'].unique()
print(peso)

['1.37kg' '1.34kg' '1.86kg' '1.83kg' '2.1kg' '2.04kg' '1.3kg' '1.6kg'
 '2.2kg' '0.92kg' '1.22kg' '2.5kg' '1.62kg' '1.91kg' '2.3kg' '1.35kg'
 '1.88kg' '1.89kg' '1.65kg' '2.71kg' '1.2kg' '1.44kg' '2.8kg' '2kg'
 '2.65kg' '2.77kg' '3.2kg' '1.49kg' '2.4kg' '2.13kg' '2.43kg' '1.7kg'
 '1.4kg' '1.8kg' '1.9kg' '3kg' '1.252kg' '2.7kg' '2.02kg' '1.63kg'
 '1.96kg' '1.21kg' '2.45kg' '1.25kg' '1.5kg' '2.62kg' '1.38kg' '1.58kg'
 '1.85kg' '1.23kg' '2.16kg' '2.36kg' '7.2kg' '2.05kg' '1.32kg' '1.75kg'
 '0.97kg' '2.56kg' '1.48kg' '1.74kg' '1.1kg' '1.56kg' '2.03kg' '1.05kg'
 '5.4kg' '4.4kg' '1.90kg' '1.29kg' '2.0kg' '1.95kg' '2.06kg' '1.12kg'
 '3.49kg' '3.35kg' '2.23kg' '?' '2.9kg' '4.42kg' '2.69kg' '2.37kg' '4.7kg'
 '3.6kg' '2.08kg' '4.3kg' '1.68kg' '1.41kg' '4.14kg' '2.18kg' '2.24kg'
 '2.67kg' '4.1kg' '2.14kg' '1.36kg' '2.25kg' '2.15kg' '2.19kg' '2.54kg'
 '3.42kg' '5.8kg' '1.28kg' '2.33kg' '1.45kg' '2.79kg' '8.23kg' '1.26kg'
 '1.84kg' '0.0002kg' '2.6kg' '2.26kg' '3.25kg' '1.59kg' '1.13kg' '1.42kg'
 '1.78kg' '1.10kg' '1.15kg' '1.27kg' '1.43kg' '2.31kg' '1.16kg' '1.64kg'
 '2.17kg' '1.47kg' '3.78kg' '1.79kg' '0.91kg' '1.99kg' '4.33kg' '1.93kg'
 '1.87kg' '2.63kg' '3.4kg' '3.14kg' '1.94kg' '1.24kg' '4.6kg' '4.5kg'
 '8.4kg' '2.73kg' '1.39kg' '2.29kg' '2.59kg' '2.94kg' '11.1kg' '1.14kg'
 '3.8kg' '6.2kg' '3.31kg' '1.09kg' '3.21kg' '1.19kg' '1.98kg' '1.17kg'
 '4.36kg' '1.71kg' '2.32kg' '4.2kg' '1.55kg' '0.81kg' '1.18kg' '2.72kg'
 '1.31kg' '0.920kg' '3.74kg' '1.76kg' '1.54kg' '2.83kg' '2.07kg' '2.38kg'
 '3.58kg' '1.08kg' '2.20kg' '0.98kg' '2.75kg' '1.70kg' '2.99kg' '1.11kg'
 '2.09kg' '4kg' '3.0kg' '0.99kg' '0.69kg' '3.52kg' '2.591kg' '2.21kg'
 '3.3kg' '2.191kg' '2.34kg' '4.0kg']

In [85]:
##Cambiamos el precio a tipo numérico, eliminando el símbolo de moneda y convirtiendo a float
##df['precio_Kg'] = pd.to_numeric(df['precio_Kg'].astype(str).str.replace('₹', '', regex=False).str.replace(',', '', regex=False),errors='coerce')
df['precio'] = pd.to_numeric(df['precio'].astype(str).str.replace('₹', '', regex=False).str.replace(',', '', regex=False), errors='coerce')

In [82]:
##Miramos si hay filas duplicadas, ya que pueden sesgar nuestro análisis y no aportan nada nuevo.
df.duplicated().sum()

np.int64(0)

In [81]:
#Eliminamos las filas duplicadas, ya que no aportan nada nuevo a nuestro análisis y pueden sesgar los resultados.
df.drop_duplicates(inplace=True)

In [ ]:
df['memoria'].value_counts()

memoria
256GB SSD                        401
1TB HDD                          209
500GB HDD                        121
512GB SSD                        112
128GB SSD +  1TB HDD              92
128GB SSD                         72
256GB SSD +  1TB HDD              71
32GB Flash Storage                35
2TB HDD                           16
512GB SSD +  1TB HDD              14
1TB SSD                           13
64GB Flash Storage                12
256GB SSD +  2TB HDD              10
256GB Flash Storage                8
16GB Flash Storage                 7
1.0TB Hybrid                       7
32GB SSD                           6
128GB Flash Storage                4
180GB SSD                          4
16GB SSD                           3
512GB SSD +  2TB HDD               3
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
1TB SSD +  1TB HDD                 2
512GB Flash Storage                2
512GB SSD +  512GB SSD             1
64GB SSD                           1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
512GB SSD +  256GB SSD             1
?                                  1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

Hacemos separacion de los tipos de procesador

In [ ]:
procesador = df['procesador'].unique()
print(procesador)

['Intel Core i5 2.3GHz' 'Intel Core i5 1.8GHz'
 'Intel Core i5 7200U 2.5GHz' 'Intel Core i7 2.7GHz'
 'Intel Core i5 3.1GHz' 'AMD A9-Series 9420 3GHz' 'Intel Core i7 2.2GHz'
 'Intel Core i7 8550U 1.8GHz' 'Intel Core i5 8250U 1.6GHz'
 'Intel Core i3 6006U 2GHz' 'Intel Core i7 2.8GHz'
 'Intel Core M m3 1.2GHz' 'Intel Core i7 7500U 2.7GHz'
 'Intel Core i7 2.9GHz' 'Intel Core i3 7100U 2.4GHz'
 'Intel Core i5 7300HQ 2.5GHz' 'AMD E-Series E2-9000e 1.5GHz'
 'Intel Core i5 1.6GHz' 'Intel Core i7 8650U 1.9GHz'
 'Intel Atom x5-Z8300 1.44GHz' 'AMD E-Series E2-6110 1.5GHz'
 'AMD A6-Series 9220 2.5GHz' 'Intel Celeron Dual Core N3350 1.1GHz'
 'Intel Core i3 7130U 2.7GHz' 'Intel Core i7 7700HQ 2.8GHz'
 'Intel Core i5 2.0GHz' 'AMD Ryzen 1700 3GHz'
 'Intel Pentium Quad Core N4200 1.1GHz'
 'Intel Celeron Dual Core N3060 1.6GHz' 'Intel Core i5 1.3GHz'
 'AMD FX 9830P 3GHz' 'Intel Core i7 7560U 2.4GHz'
 'AMD E-Series 6110 1.5GHz' 'Intel Core i5 6200U 2.3GHz'
 'Intel Core M 6Y75 1.2GHz' 'Intel Core i5 7500U 2.7GHz'
 'Intel Core i3 6006U 2.2GHz' 'AMD A6-Series 9220 2.9GHz'
 'Intel Core i7 6920HQ 2.9GHz' 'Intel Core i5 7Y54 1.2GHz'
 'Intel Core i7 7820HK 2.9GHz' 'Intel Xeon E3-1505M V6 3GHz'
 'Intel Core i7 6500U 2.5GHz' 'AMD E-Series 9000e 1.5GHz'
 'AMD A10-Series A10-9620P 2.5GHz' 'AMD A6-Series A6-9220 2.5GHz'
 'Intel Core i5 2.9GHz' 'Intel Core i7 6600U 2.6GHz'
 'Intel Core i3 6006U 2.0GHz' 'Intel Celeron Dual Core 3205U 1.5GHz'
 'Intel Core i7 7820HQ 2.9GHz' 'AMD A10-Series 9600P 2.4GHz'
 'Intel Core i7 7600U 2.8GHz' 'AMD A8-Series 7410 2.2GHz'
 'Intel Celeron Dual Core 3855U 1.6GHz'
 'Intel Pentium Quad Core N3710 1.6GHz' 'AMD A12-Series 9720P 2.7GHz'
 'Intel Core i5 7300U 2.6GHz' 'AMD A12-Series 9720P 3.6GHz'
 'Intel Celeron Quad Core N3450 1.1GHz'
 'Intel Celeron Dual Core N3060 1.60GHz' 'Intel Core i5 6440HQ 2.6GHz'
 'Intel Core i7 6820HQ 2.7GHz' 'AMD Ryzen 1600 3.2GHz'
 'Intel Core i7 7Y75 1.3GHz' 'Intel Core i5 7440HQ 2.8GHz'
 'Intel Core i7 7660U 2.5GHz' 'Intel Core i7 7700HQ 2.7GHz'
 'Intel Core M m3-7Y30 2.2GHz' 'Intel Core i5 7Y57 1.2GHz'
 'Intel Core i7 6700HQ 2.6GHz' 'Intel Core i3 6100U 2.3GHz'
 'Intel Atom x5-Z8350 1.44GHz' 'AMD A10-Series 9620P 2.5GHz'
 'AMD E-Series 7110 1.8GHz' 'Intel Celeron Dual Core N3350 2.0GHz'
 'AMD A9-Series A9-9420 3GHz' 'Intel Core i7 6820HK 2.7GHz'
 'Intel Core M 7Y30 1.0GHz' 'Intel Xeon E3-1535M v6 3.1GHz'
 'Intel Celeron Quad Core N3160 1.6GHz' 'Intel Core i5 6300U 2.4GHz'
 'Intel Core i3 6100U 2.1GHz' 'AMD E-Series E2-9000 2.2GHz'
 'Intel Celeron Dual Core N3050 1.6GHz' 'Intel Core M M3-6Y30 0.9GHz'
 'AMD A9-Series 9420 2.9GHz' 'Intel Core i5 6300HQ 2.3GHz'
 'AMD A6-Series 7310 2GHz' 'Intel Atom Z8350 1.92GHz'
 'Intel Xeon E3-1535M v5 2.9GHz' 'Intel Core i5 6260U 1.8GHz'
 'Intel Pentium Dual Core N4200 1.1GHz'
 'Intel Celeron Quad Core N3710 1.6GHz' 'Intel Core M 1.2GHz'
 'AMD A12-Series 9700P 2.5GHz' 'Intel Core i7 7500U 2.5GHz'
 'Intel Pentium Dual Core 4405U 2.1GHz' 'AMD A4-Series 7210 2.2GHz'
 'Intel Core i7 6560U 2.2GHz' 'Intel Core M m7-6Y75 1.2GHz'
 'AMD FX 8800P 2.1GHz' 'Intel Core M M7-6Y75 1.2GHz'
 'Intel Core i5 7200U 2.50GHz' 'Intel Core i5 7200U 2.70GHz'
 'Intel Atom X5-Z8350 1.44GHz' 'Intel Core i5 7200U 2.7GHz'
 'Intel Core M 1.1GHz' 'Intel Atom x5-Z8550 1.44GHz'
 'Intel Pentium Dual Core 4405Y 1.5GHz'
 'Intel Pentium Quad Core N3700 1.6GHz' 'Intel Core M 6Y54 1.1GHz'
 'Intel Core i7 6500U 2.50GHz' 'Intel Celeron Dual Core N3350 2GHz'
 'AMD E-Series 9000 2.2GHz' 'Intel Core M 6Y30 0.9GHz'
 'AMD A9-Series 9410 2.9GHz']

In [ ]:
##Corrijo 'Samsung Cortex A72&A53 2.0GHz' 'AMD E-Series 9000 2.2GHz'y dejo solo la referencia a AMD, ya que es un error de tipeo y no existe el procesador Samsung Cortex A72&A53 2.0GHz, sino que es un error de tipeo y se refiere al procesador AMD E-Series 9000 2.2GHz.
df['procesador'] = df['procesador'].str.replace('Samsung Cortex A72&A53 2.0GHz', 'AMD E-Series 9000 2.2GHz', regex=False)

In [ ]:
# Defino procesadores de cada marca para categorizar los procesadores en categorías más amplias, lo que facilitará el análisis y la visualización de
##procesador_intel = ['Intel Core i3', 'Intel Core i5', 'Intel Core i7', 'Intel Core i9']
##procesador_amd = ['AMD Ryzen 3', 'AMD Ryzen 5', 'AMD Ryzen 7', 'AMD Ryzen 9']
##procesador_android = ['Snapdragon 8 Gen 2', 'Snapdragon 8cx Gen 3']

# Create a mapping function to categorize processors
##def categorizar_procesador(proc):
##    if proc in procesador_intel:
##        return 'Intel'
##    elif proc in procesador_amd:
##        return 'AMD'
##    else proc in procesador_android:
##        return 'Snapdragon'

Hacemos separacion por sistema operativo

In [80]:
sistema_operativo = df['sistema_operativo'].unique()
print(sistema_operativo)

##Lista de sistemas operativos que habian
##'macOS' 'No OS' 'Windows 10' 'Mac OS X' 'Linux' 'Windows 10 S'
##'Chrome OS' 'Windows 7' 'Android'

['macOS' 'No OS' 'Windows' 'Linux' 'Chrome OS' 'Android']

In [79]:
##Unificamos los sistemas operativos Windows 10 y Windows 11 en una sola categoría llamada Windows, ya que ambos son versiones del mismo sistema operativo y no queremos que la variable sistema_operativo tenga demasiadas categorías diferentes que puedan dificultar el análisis.
df['sistema_operativo'] = df['sistema_operativo'].str.replace('Windows 10', 'Windows', regex=False)
df['sistema_operativo'] = df['sistema_operativo'].str.replace('Windows 7', 'Windows', regex=False)
df['sistema_operativo'] = df['sistema_operativo'].str.replace('Windows S', 'Windows', regex=False)
df['sistema_operativo'] = df['sistema_operativo'].str.replace('Windows 11', 'Windows', regex=False)     
df['sistema_operativo'] = df['sistema_operativo'].str.replace('Mac OS X', 'macOS', regex=False)

Hacemos separacion de los tipos de Laptps

In [78]:
tipo_laptop = df['tipo_laptop'].unique()
print(tipo_laptop)

['Ultrabook' 'Notebook' 'Gaming' '2 in 1 Convertible' 'Workstation']